/** @type {import('postcss-load-config').Config} */
const config = {
  plugins: {
    // Always include these plugins
    'tailwindcss': {},
    'autoprefixer': {},

    // Only include optimization plugins in production
    ...(process.env.NODE_ENV === 'production' && {
      // Minify CSS in production
      'cssnano': {
        preset: ['default', {
          discardComments: {
            removeAll: true,
          },
          normalizeWhitespace: true,
          minifyFontValues: true,
          colormin: true,
          reduceIdents: false, // Can break animations
          zindex: false, // Can break z-index layering
        }],
      },

      // Purge unused CSS in production
      '@fullhuman/postcss-purgecss': {
        content: [
          './src/pages/**/*.{js,jsx,ts,tsx}',
          './src/components/**/*.{js,jsx,ts,tsx}',
          './src/app/**/*.{js,jsx,ts,tsx}',
        ],
        defaultExtractor: content => content.match(/[\w-/:]+(?<!:)/g) || [],
        safelist: {
          standard: [
            /^(dark|light)/,
            /^(h-|w-|min-h-|min-w-|max-h-|max-w-)/,
            /^(block|flex|grid|hidden)/,
            /^(absolute|relative|fixed|sticky)/,
            /^(mt-|mb-|ml-|mr-|my-|mx-|pt-|pb-|pl-|pr-|py-|px-)/,
            /^(text-|bg-|border-|rounded-)/,
            /^(opacity-)/,
            /^(transform|rotate|scale|translate)/,
            /^(transition)/,
            /^(shadow-)/,
            /^(from-|to-|via-)/,
            /^(blur-)/,
            /^(pointer-events-)/,
            /^(z-)/,
            /^(inset-)/,
            /^(overflow-)/,
            /^(gap-)/,
            /^(space-)/,
            /^(col-|row-)/,
            /^(items-|justify-|content-)/,
            /^(cursor-)/,
            /^(outline-)/,
            /^(ring-)/,
            /^(stroke-|fill-)/,
            /^(object-)/,
            /^(font-)/,
            /^(tracking-)/,
            /^(leading-)/,
            /^(whitespace-)/,
            /^(align-)/,
            /^(appearance-)/,
            /^(placeholder-)/,
            /^(backdrop-)/,
            /^(animate-)/,
            /^(delay-)/,
            /^(duration-)/,
            /^(ease-)/,
            /^(will-change-)/,
            /^(origin-)/,
            /^(accent-)/,
            /^(caret-)/,
            /^(decoration-)/,
            /^(grayscale-)/,
            /^(hue-rotate-)/,
            /^(invert-)/,
            /^(saturate-)/,
            /^(sepia-)/,
            /^(drop-shadow-)/,
            /^(mix-blend-)/,
            /^(filter)/,
            /^(backdrop-filter)/,
            /^(divide-)/,
            /^(overscroll-)/,
            /^(scroll-)/,
            /^(snap-)/,
            /^(touch-)/,
            /^(select-)/,
            /^(break-)/,
            /^(box-)/,
            /^(float-)/,
            /^(clear-)/,
            /^(isolation-)/,
            /^(object-)/,
            /^(overflow-)/,
            /^(overscroll-)/,
            /^(position-)/,
            /^(top-|right-|bottom-|left-)/,
            /^(visible|invisible)/,
            /^(collapse|separate)/,
            /^(table-)/,
            /^(border)/,
            /^(bg-)/,
            /^(gradient-)/,
            /^(from-|via-|to-)/,
            /^(stroke-)/,
            /^(fill-)/,
            /^(list-)/,
            /^(columns-)/,
            /^(aspect-)/,
            /^(container)/,
            /^(prose)/,
            /^(sr-only)/,
            /^(not-sr-only)/,
          ],
          deep: [
            /dark:/,
            /light:/,
            /data-\[/,
            /aria-\[/,
            /^:(hover|focus|active|visited|disabled|enabled|checked|first|last|odd|even|focus-within|focus-visible)/,
          ],
          greedy: [
            /^class=/,
            /^className=/,
          ],
        },
      },
    }),
  },
};

export default config;
